/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:db46978d-5050-4a08-a996-e95cf6b31a50",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IaGRtkkYg",
    "aws_user_pools_web_client_id": "37u65ts75l6p3jmcfe13l6lg58",
    "oauth": {},
    "aws_user_files_s3_bucket": "carddate152028-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
